### ISSUE TITLE
Metastore list split request from merger pipeline startup timeout with a PoolTimedOut error.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4579] opened 2024-02-14 03:12 UTC
@fmassot I did not find any issue about this. Is there one?

**Comment by guilload** [comment] 2024-02-14 13:23
I'll try to reproduce it on Cicada today. If you've just tested this on `main,` I merged two PRs that might have helped yesterday.

**Comment by guilload** [comment] 2024-03-08 18:56
It seems to be fixed. It was most likely an issue with the connection pooler in front of the DB, which disappeared when we switched to direct connections.

**Closed by guilload** 2024-03-08 18:56 UTC
Labels: bug
