### ISSUE TITLE
Reduce split size variance coming from the merge 

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#669] opened 2021-10-15 09:42 UTC
Today, merged splits can have a size between `max_merge_docs` and `2 * max_merge_docs`. 

It would be nice to limit the size variation to something like `max_merge_docs` and `1.5 * max_merge_docs`.

**Comment by fulmicoton** [comment] 2022-03-29 02:23
duplicate of #713

**Closed by fulmicoton** 2022-03-29 02:23 UTC
Labels: enhancement
