### ISSUE TITLE
Race condition in unit test  test_byte_range_cache_doesnt_merge_unnecessarily

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4358] opened 2024-01-10 01:44 UTC
I just got this error. A rerun did not reproduce.
I just ran cargo test from the quickwit-storage directory.

---- cache::byte_range_cache::tests::test_byte_range_cache_doesnt_merge_unnecessarily stdout ----
thread 'cache::byte_range_cache::tests::test_byte_range_cache_doesnt_merge_unnecessarily' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `4`', quickwit-storage/src/cache/byte_range_cache.rs:517:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by fulmicoton** [comment] 2024-01-10 01:53
Reproduced this time with


---- cache::byte_range_cache::tests::test_byte_range_cache_doesnt_merge_unnecessarily stdout ----
thread 'cache::byte_range_cache::tests::test_byte_range_cache_doesnt_merge_unnecessarily' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `4`', quickwit-storage/src/cache/byte_range_cache.rs:517:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by trinity-1686a** [comment] 2024-01-10 11:07
I can't reproduce with `cargo nextest` (which isolate tests in their own process), or with `cargo test -- --test-threads=1`, but I can with just `cargo test` (and more often with `cargo test -- cache::`, which maximize the chances of the wrong tests being run in parallel)

`CACHE_METRICS_FOR_TESTS` is a mutable shared state between all tests. if multiple tests manipulating it are executed in parallel in the same process, the result is racy.
the course of action can be one of:
- require that tests are run either with nextest, or with `-- --test-threads=1`
- introduce [some crate](https://crates.io/crates/serial_test) which force running some tests serialized
- remove that particular assertion, but I'd prefer to keep it as it tests something that could easily be done wrong (updating properly the metrics when we merged multiple ranges)

@fulmicoton wdyt?

**Closed** 2024-01-30 10:25 UTC
Labels: bug
