### ISSUE TITLE
Deleting and recreate an index can lead to unexpected behavior for the ingest API

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3047] opened 2023-03-17 22:31 UTC
Deletion and recreation of an index can lead to several issues on the indexing and merge pipelines as reported in #3035 and #3041.

It is also an issue for the ingest API. Note that we use the index ID for the ingest queue ID.

If we delete an index, we have no way to ensure that ingest queues related to this index are deleted on all indexers. If we recreate an index with the same ID, the ingest API source will use the old queues and this can lead to indexing documents present in the old queues.

**Comment by guilload** [comment] 2023-07-18 02:14
Duplicate of #3559.

**Closed by guilload** 2023-07-18 02:14 UTC
Labels: bug
