### ISSUE TITLE
VRL support for the ingest APi

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3549] opened 2023-06-13 23:14 UTC
Right now VRL is not supported for the PushAPI (!?)

Can we add move this to the docmapper?

**Comment by trinity-1686a** [comment] 2023-06-13 23:35
duplicate of #3549

(for details, the ingest API technically supports VRL, but you can't configure it without messing manually with the metastore)

**Closed by trinity-1686a** 2023-06-13 23:35 UTC
Labels: enhancement

**Comment by fulmicoton** [comment] 2023-06-14 00:27
thx
