### ISSUE TITLE
Add the ability to wait for documents to be published before responding to clients

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2807] opened 2023-02-13 13:40 UTC
Elasticsearch provides a way to wait for indexing operations to be visible to searchers using the `refresh=wait_for` query parameter, it would be useful to have something similar in Quickwit waiting for the split containing the docs to be published especially for benchmarking. 

I believe this will be something we'll need to do anyway for the ES-compatible API #2653

**Comment by fmassot** [comment] 2023-02-14 10:14
@ChillFish8 seems like a duplicate of #2699

**Comment by ChillFish8** [comment] 2023-02-14 10:16
It's similar but I don't think it's the same, that ticket describes forcing a commit/publish from what I can tell rather than just waiting for a publish to complete (which is what the refresh=wait_for parameter is on ES iirc)

**Closed** 2023-02-16 02:07 UTC
Labels: enhancement
