### ISSUE TITLE
The CLI merge command exits with error

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#1981] opened 2022-09-20 15:58 UTC
The merge command is supposed to keep quickwit merge pipeline running till canceled.
Currently, it exists shortly after starting with this error.
```
...
2022-09-20T08:26:04.348Z  INFO {actor=quickwit_indexing::actors::indexing_service::IndexingService}:{msg_id=1}:: quickwit_actors::spawn_builder: actor-exit actor_id=IndexingPipeline-shy-wrDU exit_status=Success
2022-09-20T08:26:04.352Z  INFO {actor=Scheduler}: quickwit_actors::spawn_builder: actor-exit actor_id=Scheduler-icy-KQTU exit_status=Killed
2022-09-20T08:26:04.352Z ERROR {actor=Scheduler}: quickwit_actors::actor: actor-failure actor_name="Scheduler-icy-KQTU" actor_exit_status=Killed
2022-09-20T08:26:04.353Z  INFO {actor=quickwit_indexing::actors::indexing_service::IndexingService}: quickwit_actors::spawn_builder: actor-exit actor_id=quickwit_indexing::actors::indexing_service::IndexingService-patient-AXPK exit_status=Killed
2022-09-20T08:26:04.353Z ERROR {actor=quickwit_indexing::actors::indexing_service::IndexingService}: quickwit_actors::actor: actor-failure actor_name="quickwit_indexing::actors::indexing_service::IndexingService-patient-AXPK" actor_exit_status=Killed
```

To keep it running we can use SourceParams::Void https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-indexing/src/actors/indexing_service.rs#L344

**Comment by fulmicoton** [comment] 2022-09-21 03:43
It is supposed to only exit if no one holds its mailbox. I assume you want it to run so that you can add a source/an indexing pipeline in the future. How do you get its mailbox then?

**Comment by evanxg852000** [comment] 2022-09-21 09:19
Discussing with @fmassot yesterday, it appeared that the only advantage of having it is testing merge in action. There is the question of whether we should ditch it.
Indeed, when you keep it running, you cannot get the mailbox held by the void source.
My intent is that this command will periodically fetch splits produced by indexing pipelines with `source_id` and send it to the internal merge planner mailbox.  We update the command line params to take the source_id you want this merge command to work: `quickwit index merge --index Wikipedia --source_id kafka1`

**Comment by fmassot** [comment] 2022-11-01 16:11
@guilload we still have a log error... but it's the expected behavior of the actor framework, I opened an issue to discuss this point #2150

**Comment by guilload** [comment] 2022-11-01 16:35
Ok. I thought the issue was specific to the merge command. This is actually a duplicate of #1439. I'll close both and keep #2150 open.

**Closed by guilload** 2022-11-01 16:35 UTC
Labels: bug
