### ISSUE TITLE
Extract timestamp range to enable pruning

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3256] opened 2023-05-03 11:03 UTC
We can sometime identify that a range query on the timestamp is implied by the AST.
In that case, we should extract the boundaries and enable timestamp pruning.

related with #3194 but higher priority

(@fmassot  I opened an issue since it is actually different from #3194)

**Comment by trinity-1686a** [comment] 2023-05-03 12:46
duplicate of #3169 ?

**Closed** 2023-05-26 12:15 UTC
Labels: enhancement
