### ISSUE TITLE
Fix flaky tests metastore

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5130] opened 2024-06-15 13:52 UTC
https://github.com/quickwit-oss/quickwit/actions/runs/9515949965/job/26231236296

```

failures:
    metastore::postgres::metastore::tests::common_tests::test_metastore_find_index_template_matches

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 155 filtered out; finished in 0.33s


--- TRY 1 STDERR:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_find_index_template_matches ---
thread 'metastore::postgres::metastore::tests::common_tests::test_metastore_find_index_template_matches' panicked at quickwit-metastore/src/tests/template.rs:226:5:
assertion `left == right` failed
  left: 2
 right: 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   RETRY 2/3 [         ] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_find_index_template_matches
        PASS [   0.370s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_get_index_template
        PASS [   0.676s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_shards
  TRY 2 FAIL [   0.271s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template

--- TRY 2 STDOUT:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template ---

running 1 test
test metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template ... FAILED

failures:

failures:
    metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 155 filtered out; finished in 0.19s


--- TRY 2 STDERR:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template ---
thread 'metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template' panicked at quickwit-metastore/src/tests/template.rs:80:5:
assertion `left == right` failed
  left: 3
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   RETRY 3/3 [         ] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template
        PASS [   0.572s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_source
        PASS [   4.092s] quickwit-metastore metastore::file_backed::tests::common_tests::test_metastore_split_update_timestamp
  TRY 2 FAIL [   0.550s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates

--- TRY 2 STDOUT:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates ---

running 1 test
test metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates ... FAILED

failures:

failures:
    metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 155 filtered out; finished in 0.39s


--- TRY 2 STDERR:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates ---
thread 'metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates' panicked at quickwit-metastore/src/tests/template.rs:345:5:
assertion `left == right` failed
  left: 3
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   RETRY 3/3 [         ] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_index_templates
        PASS [   0.872s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_delete_splits
  TRY 3 FAIL [   0.403s] quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template

--- TRY 3 STDOUT:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template ---

running 1 test
test metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template ... FAILED

failures:

failures:
    metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 155 filtered out; finished in 0.32s


--- TRY 3 STDERR:        quickwit-metastore metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template ---
thread 'metastore::postgres::metastore::tests::common_tests::test_metastore_create_index_template' panicked at quickwit-metastore/src/tests/template.rs:80:5:
assertion `left == right` failed
  left: 2
 right: 1
note: run with `RUST_BACKTRACE=1` environment var
```

**Comment by guilload** [comment] 2024-06-15 18:04
Duplicate of #5127

**Closed by guilload** 2024-06-15 18:04 UTC
Labels: bug
