### ISSUE TITLE
dangling port in tests sometimes

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#262] opened 2021-07-09 15:48 UTC
In some scenarios there is a sub process spawned and not killed at the end of the test execution.

QUICKWIT_ENV=LOCAL cargo test --all-features -- --nocapture

```
thread 'test_all_with_s3_localstack_internal_api' panicked at 'Cannot read output: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', quickwit-cli/tests/cli.rs:409:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_all_with_s3_localstack_internal_api ... FAILED
Command failed: Artillery :: I/O error occurred: Address already in use (os error 98)
thread 'test_all_with_s3_localstack_cli' panicked at 'Cannot read output: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', quickwit-cli/tests/cli.rs:327:10
```

In the serve case you can find the zombie process via `netstat -tulpn | grep :8182`

We should kill the whole process group to avoid zombie processes in the tests or have some other kind of clean up to avoid this.

**Comment by fmassot** [comment] 2021-08-30 19:31
the cli tests are spawning using `std::process::Command` and each time there is a failing test we do not `server_process.kill()` and I think the issue is coming from there.

**Comment by PSeitz** [comment] 2021-08-30 21:57
In that case we could wrap all Commands and implement drop on the handle to kill dangling processes

**Comment by PSeitz** [comment] 2022-05-06 03:00
A long time ago, I think it only was an issue when there was a panic.

**Comment by fmassot** [comment] 2022-05-06 09:20
Yes, I think it only happens when an error happens during the test

**Comment by guilload** [comment] 2022-05-06 14:48
Let's close this issue for now. Feel free to reopen if you observe a new occurrence.

**Closed by guilload** 2022-05-06 14:48 UTC
Labels: bug, enhancement, low-priority
