### ISSUE TITLE
Slow missing term lookup in tantivy?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3964] opened 2023-10-16 11:23 UTC
in quickwit we observed queries with a single missing term to be extermely slow. The term warmup shows an insanely high `busy_ns` in the trace. (200ms per split) The cause is unknown.

To reproduce, on GH archive, search for `actor.tlogin:fulmicoton` (note the typo).

A likely cause could be the sstable lookup not behaving properly when the term is missing. (unsure)

**Comment by fulmicoton** [comment] 2023-10-17 03:06
I confirmed this happens on a normal S3 index too.

**Comment by trinity-1686a** [comment] 2023-10-17 15:20
the issue is not in missing terms, but rather in the field for `actor` being much bigger than the one for `actor.login` for that docmapper.
It's large enough that decoding the index of the field's sstable is long. There is no bug per say, rather a need for an optimization in sstable load, such as a multi-layer index (https://github.com/quickwit-oss/tantivy/issues/1948) so we don't have to decode the entire large index

**Comment by trinity-1686a** [comment] 2023-12-06 11:20
fixed by https://github.com/quickwit-oss/tantivy/pull/2268, but we'll wait for the corresponding commit to be pulled before closing

**Comment by trinity-1686a** [comment] 2023-12-27 12:12
tantivy updated in #4325

**Closed by trinity-1686a** 2023-12-27 12:12 UTC
Labels: bug
