### ISSUE TITLE
When the index is recreated, the indexer will panic

### ISSUE THREAD

**Issue by guidao** [quickwit-oss/quickwit#1988] opened 2022-09-21 09:54 UTC
**Describe the bug**
When the index is recreated, the indexer will panic
```
thread 'blocking-40' panicked at 'called `Result::unwrap()` on an `Err` value: ColumnDecode { index: "0", source: UnexpectedNullError }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.6.1/src/row.rs:73:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
```

**Steps to reproduce (if applicable)**

1.  quickwit index delete --index logs
2.  quickwit index create --index-config logs.yaml
3.  restart indexer

**Expected behavior**
Not Panic.

If I insert the following data manually, it will not panic.
```
metastore=# insert into delete_tasks(opstamp, index_id, delete_query_json) values(0, 'logs', '{}');
```

It seems to be related to this function.
https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs#L740

**Comment by PSeitz** [comment] 2022-09-21 10:54
@guidao do you delete the index while the indexer is running?

**Comment by guidao** [comment] 2022-09-21 12:15
yes.

**Comment by guilload** [comment] 2022-09-21 19:21
Thank you for your report, @guidao. The bug was fixed by #1992.

**Closed by guilload** 2022-09-21 19:21 UTC
Labels: bug

**Comment by guilload** [comment] 2022-09-21 19:45
BTW, @guidao, what is the volume of deletes that you perform? This functionality was designed for a low frequency/volume of deletes to address compliance use cases.

I'm also afraid that the functionality is still half-baked since we haven't landed all our work on deletes yet in [tantivy](https://github.com/quickwit-oss/tantivy).

**Comment by guidao** [comment] 2022-09-22 02:34
About 30,000 splits of index. Thanks for the heads up, we are testing the index configuration parameters.
