### ISSUE TITLE
Improve readability of aggregation error response

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3281] opened 2023-05-06 13:25 UTC
Example::

```json
{"query":"*","aggs":{"1":{"avg":{}}}}
```

```json
{"message":"Invalid aggregation request: data did not match any variant of untagged enum QuickwitAggregations"}
```

**Comment by fulmicoton** [comment] 2023-05-07 03:50
@PSeitz if we already have a ticket for this, can you close one of the two?
It think it will require an adhoc serializer... let me know if you need help.

**Comment by PSeitz** [comment] 2023-05-07 10:44
The issue is that there's another `#[serde(untagged)]`. It seems unnecessary to merge the two requests. Can we unsplit it?
@fulmicoton  @guilload 

```rust
/// Available aggregation types.
#[derive(Debug, Clone, Deserialize)]
#[serde(untagged)]
pub enum QuickwitAggregations {
    /// Aggregation used by the Jaeger service to find trace IDs that match a
    /// [`quickwit_proto::jaeger::storage::v1::FindTraceIDsRequest`].
    FindTraceIdsAggregation(FindTraceIdsCollector),
    /// Your classic Tantivy aggregation.
    TantivyAggregations(Aggregations),
}
```

**Comment by fulmicoton** [comment] 2023-05-07 13:27
Yes I think it would be a good idea to remove this untagged.

It might be painful to add a new type of request (as in RPC service), but we can probably simply add a field in LeafRequest for tracing stuff.

**Comment by PSeitz** [comment] 2023-05-24 03:33
This is fixed by only returning the tantivy error in case aggregation parsing fails.
The correct solution would be to split tracing and tantivy aggregations.

**Closed** 2023-05-24 03:33 UTC
Labels: enhancement
