### ISSUE TITLE
AWS Kensis tests are flaky during code coverage.

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#3061] opened 2023-03-21 15:20 UTC
During the code cov run the Kensis test seems to fail fairly often as a flaky test.

```
---- source::kinesis::kinesis_source::tests::test_kinesis_source stdout ----
thread 'source::kinesis::kinesis_source::tests::test_kinesis_source' panicked at 'assertion failed: `(left == right)`
  left: `[b"Record #00", b"Record #01", b"Record #10", b"Record #11"]`,
 right: `["Record #00", "Record #01", "Record #11"]`', quickwit-indexing/src/source/kinesis/kinesis_source.rs:572:13


failures:
    source::kinesis::kinesis_source::tests::test_kinesis_source

test result: FAILED. 138 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 54.55s

error: test failed, to rerun pass `-p quickwit-indexing --lib`
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/1.68-x86_64-unknown-linux-gnu/bin/cargo test --tests --manifest-path /home/runner/work/quickwit/quickwit/quickwit/Cargo.toml --target-dir /home/runner/work/quickwit/quickwit/quickwit/target/llvm-cov-target --all-features` (exit status: 101)
```

**Comment by guilload** [comment] 2023-03-21 15:21
Duplicate of #2872.

**Closed by guilload** 2023-03-21 15:21 UTC
Labels: bug
