### ISSUE TITLE
coverage flaky due to test_kinesis_source

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#3199] opened 2023-04-19 06:31 UTC
```
failures:

---- source::kinesis::kinesis_source::tests::test_kinesis_source stdout ----
thread 'source::kinesis::kinesis_source::tests::test_kinesis_source' panicked at 'assertion failed: `(left == right)`
  left: `[b"Record #00", b"Record #01", b"Record #10", b"Record #11"]`,
 right: `["Record #00", "Record #01", "Record #11"]`', quickwit-indexing/src/source/kinesis/kinesis_source.rs:572:13


failures:
    source::kinesis::kinesis_source::tests::test_kinesis_source

test result: FAILED. 142 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 56.13s
```

**Comment by fmassot** [comment] 2023-04-19 11:33
Duplicate of #2872

**Closed by fmassot** 2023-04-19 11:33 UTC
