### ISSUE TITLE
k8s support

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1238] opened 2022-03-29 08:44 UTC
We want quickwit to be easy to deploy on k8s.

One issue that we have is how do we start the cluster formation via scuttlebutt.

It requires to get connected to a small set of peers that we call peer nodes.

It is tempting to put a k8s service in front of our nodes and set the peer node IP to the service IP.
The default of this approach is that the service might connect us to ourselves, creating a bunch of 
partition in our cluster.

Another solution might be to relly on the k8s API to get our peers.

Another solution could be to rely on a headless service and list DNS entires.

Another problem that we have is that we may have nodes dedicated to a specific service.
For instance: an indexing only node and 2 search only node.

How should we deal with this? Should we have a quickwit headless service tied will all quickwit nodes, and then 
several specific services tied to specific deployments?

etc.

**Comment by guilload** [comment] 2022-10-31 23:57
Duplicate of #1658.

**Closed by guilload** 2022-10-31 23:57 UTC
Labels: enhancement
