### ISSUE TITLE
splits are not in a deletable state

### ISSUE THREAD

**Issue by dojiong** [quickwit-oss/quickwit#3847] opened 2023-09-19 02:40 UTC
I found some errors in quickwit-indexer recently:
```
message: quickwit_actors::spawn_builder: actor-failure cause=Failed to publish splits.

Caused by:
Splits `["01HAN8GBZ3F0NQFE7GBKWAC4R6"]` are not in a deletable state. exit_status=Failure(Failed to publish splits.

Caused by:
Splits `["01HAN8GBZ3F0NQFE7GBKWAC4R6"]` are not in a deletable state.)
```

After some days of logging (more logs on merge pipeline's splits tracing), I'm almost certain it's caused by:
1. merge-pipeline:publisher finished its works, passed some splits to planner's mailbox
2. merge-pipeline crashed with some reason (upload-to-object-store-fail in my scene)
3. merge-pipeline respawn the whole pipeline after a period
4. merge-pipeline:planner created, pull all the splits from metastore (*includes the splits from step-1*)
5. merge-pipeline:planner planned to merge splits from step-4, passed it to downstream
6. merge-pipeline:planner received the NewSplits message from step-1, then planned to merge

step-5/step-6 started two task contains the same splits(not all the same)

------
Temporary fix: clear the planner's inbox before respawn merge-pipeline

Futher question: how to avoid similar message problems in actor model

quickwit version: v0.6.2

**Comment by dojiong** [comment] 2023-09-20 02:00
@fulmicoton Is there a better plan to fix these problems (dead actor's messages)?

**Comment by fulmicoton** [comment] 2023-09-20 02:11
@dojiong First congratulations on understanding our indexing/merge pipeline in depth.

This bug is most likely a duplicate of #3627. Are you working with @geek-frio by any chance?

While investigating with the logs I had access to, I came down to the same conclusion as you, and then ruled out that possible cause due to some guard in the code, and due to the absence of merge pipeline error in the log... but maybe I overlook something.

The temporary fix you suggest is definitely not a good idea.
Let me reprioritize this. This bug is important.

**Comment by dojiong** [comment] 2023-09-20 02:35
I read that issue, it was also caused by duplicate plans.

According to my dig on the merge-planner's code, the most possible reason is the NewSplits message and merge-planner-init contains the same split (I also checked related actor's lifetime, it's not the reason in my scene).

This is my temprary fix: @geek-frio
```diff
diff --git a/quickwit/quickwit-actors/src/mailbox.rs b/quickwit/quickwit-actors/src/mailbox.rs
index e1571682..e23fd94d 100644
--- a/quickwit/quickwit-actors/src/mailbox.rs
+++ b/quickwit/quickwit-actors/src/mailbox.rs
@@ -369,7 +369,7 @@ impl<A: Actor> Inbox<A> {
         self.rx.recv_high_priority().await
     }
 
-    pub(crate) fn try_recv(&self) -> Result<Envelope<A>, RecvError> {
+    pub fn try_recv(&self) -> Result<Envelope<A>, RecvError> {
         self.rx.try_recv()
     }
 
diff --git a/quickwit/quickwit-indexing/src/actors/merge_pipeline.rs b/quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
index 8fc978fb..395385c2 100644
--- a/quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
+++ b/quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
@@ -233,6 +233,9 @@ impl MergePipeline {
         self.statistics.num_spawn_attempts += 1;
         self.kill_switch = ctx.kill_switch().child();
 
+        // clear dirty messages
+        while self.merge_planner_inbox.try_recv().is_ok() {}
```

-----
Anyway, `not in a deletable state` **no longer appears** after this fix.

**Comment by dojiong** [comment] 2023-09-20 03:30
I got another `not in a deletable state` error right now. It's the same mailbox/init duplicate problem, but another message order:
1. Upstream actor send SplitsUpdate message to merge-publisher
2. merge-pipeline crashed
3. merge-pipeline respawn
5. merge-publisher process publish tasks, publish splits, then send NewSplits to merge-planner
6. merge-planner created, get all the splits from metastore (includes splits from step-5), then planned
7. merge-planner received the NewSplits message from step-5, process it, failed

step-6/step-7 started two task contains the same splits(not all the same)

-----
The temporary fix [above](https://github.com/quickwit-oss/quickwit/issues/3847#issuecomment-1726792178) reduced the probability of the problem, not solved it.

I think merge-planner should not call `send_merge_ops` on actor::initialize, just driven by messages. @fulmicoton

**Comment by dojiong** [comment] 2023-09-22 03:59
The `deletable` problem does not appear after two days (with the patch of clear-planner-inbox).
I reanalyze the case [above](https://github.com/quickwit-oss/quickwit/issues/3847#issuecomment-1726829067), found something is impossible.

timeline:
1. mege-uploader-task(merge-splits replated task) failed, trigger kill-switch
2. merge-uploader-task(splits-publish related task) finished, send SplitsUpdate to publisher
3. merge-uploader been killed
4. merge-pipeline failed
5. merge-pipeline respawn, get all the splits from metastore
6. merge-publisher started, received SplitsUpdate(I compare the splits with step-2, it's the same)
7. merge-publisher published, send NewSplits to planner
8. merge-planner started with splits which contains splits from step-2

my problem is:
1. merge-publisher's mailbox is recreated on merge-pipeline spawn, why merge-publisher can receive (step-6) the message from previous epoch (step-2)?
2. why splits fetched at step-5 contains splits from step-2? It should not be published-state until step-7

@fulmicoton

----

I may not get more `deletable` logs after the [temporary fix](https://github.com/quickwit-oss/quickwit/issues/3847#issuecomment-1726792178), could we move forward base on the known problem:
**merge-planner start from all the splits and the mailboxes of previous epoch contains the same splits**.

**Comment by fmassot** [comment] 2023-09-25 10:42
@dojiong thanks for the detailed reports.

>  why merge-publisher can receive (step-6) the message from previous epoch (step-2)?
It should not be possible indeed.

> why splits fetched at step-5 contains splits from step-2? It should not be published-state until step-7
Agreed. I don't know how this can happen.

Can you share the logs? I can try to create a test that reproduces the steps and check what's happening.

**Comment by dojiong** [comment] 2023-09-26 01:09
@fmassot The last log of `deletable problem` has been automatically cleaned(that problem only occurred once after the temporary fix I posted above)

**Comment by dojiong** [comment] 2023-09-28 03:31
#3854 does not fix the problem. I got another `deletable problem`  after that patch.

I got the full timeline with more logs:
1. merge-publisher send a NewSplits to merge-planner, successed
2. merge-publisher send another NewSplits to merge-planner, outof capacity, await on mailbox
3. merge-pipeline crashed
4. merge-pipeline respawned, get all splits from metastore(includes splits from step-1/2)
5. merge-planner received NewSplits from step-1, planned, send splits to downstream(includes splits from step-2)
6. merge-planner received NewSplits from step-2, planned, duplicated with step-5

@fulmicoton  we should clean the planner's mailbox when spawning the merge-pipeline finally? (the temporary fix I used fist only use `try_recv`, it only missed some async message in rare)

**Comment by fulmicoton** [comment] 2023-09-28 06:16
You are suggesting draining the mailbox before getting the state from the metastore right?
This is a good idea but we could technically still be at risk of a similar bug, coming from the indexing pipeline this time.

The race condition I am thinking of is very unlikely but would look like 
1. indexing publisher publishes to metastore successfully
2. indexing publisher sends new_split message. 
3. merge pipeline fails and restart.
4. indexing pipeline drain the mailbox.
5. indexing pipeline fetchs list of splits from metastore
6. merge pipeline gets respawned
7. send new split somehow worked out here.

I have a more defensive fix in mind. Can I create a PR and add you as reviewer?

**Comment by dojiong** [comment] 2023-09-28 06:20
> I have a more defensive fix in mind. Can I create a PR and add you as reviewer?

always oncall

**Comment by fulmicoton** [comment] 2023-09-28 07:57
draft PR here #3891

**Closed** 2023-10-03 09:42 UTC
Labels: bug, high-priority
