### ISSUE TITLE
REST server returns 200 OK for endpoints which should return 404s

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2830] opened 2023-02-16 14:33 UTC
While creating an index via the rest API I accidentally used just the base address of `http://127.0.0.1:7280`, unexpectedly, this returned a 200 OK from the POST request with a JSON body. It shouldn't as it's incredibly confusing to then wonder why the index doesn't actually appear.

I suspect this is an issue for any endpoints which don't exist, maybe our 404 handlers isn't working correctly?

**Comment by fmassot** [comment] 2023-02-16 14:48
It's probably related to the redirection to `/ui/search` endpoint :/

Are you sure it's a 200 and not a 301?

**Comment by ChillFish8** [comment] 2023-02-16 14:58
It's definitely a 200, which is why I was really confused when debugging 😓

**Comment by fmassot** [comment] 2023-02-23 09:06
@ChillFish8 can you give a curl example? I can't reproduce the issue.

**Comment by fmassot** [comment] 2023-02-23 23:47
@ChillFish8 should we close it?

**Comment by ChillFish8** [comment] 2023-02-24 00:10
Yes I think so 👍

**Comment by fmassot** [comment] 2023-02-27 23:14
ping @ChillFish8 :)

**Comment by ChillFish8** [comment] 2023-02-27 23:36
Good reminder 😅 

Yes, I can reproduce this:

````
curl --request POST \
  --url http://127.0.0.1:7280/ \
  --header 'Content-Type: application/json' \
  --data '	{
		"version": "0.4",
		"index_config": {
			"version": "0.4",
			"index_id": "gh-archive",
			"index_uri": "file:///quickwit/qwdata/indexes/gh-archive",
			"doc_mapping": {
				"field_mappings": [
					{
						"name": "id",
						"type": "u64",
						"fast": true,
						"indexed": true,
						"stored": true
					},
					{
						"name": "created_at",
						"type": "datetime",
						"fast": true,
						"indexed": true,
						"input_formats": [
							"unix_timestamp"
						],
						"output_format": "unix_timestamp_secs",
						"precision": "seconds",
						"stored": true
					},
					{
						"name": "event_type",
						"type": "text",
						"fast": false,
						"fieldnorms": false,
						"indexed": true,
						"stored": true,
						"tokenizer": "raw"
					},
					{
						"name": "title",
						"type": "text",
						"fast": false,
						"fieldnorms": false,
						"indexed": true,
						"record": "position",
						"stored": true,
						"tokenizer": "default"
					},
					{
						"name": "body",
						"type": "text",
						"fast": false,
						"fieldnorms": false,
						"indexed": true,
						"record": "position",
						"stored": true,
						"tokenizer": "default"
					}
				],
				"tag_fields": [],
				"store_source": true,
				"timestamp_field": "created_at",
				"mode": "lenient",
				"max_num_partitions": 200
			},
			"indexing_settings": {
				"commit_timeout_secs": 60,
				"docstore_compression_level": 8,
				"docstore_blocksize": 1000000,
				"split_num_docs_target": 10000000,
				"merge_policy": {
					"type": "stable_log",
					"min_level_num_docs": 100000,
					"merge_factor": 10,
					"max_merge_factor": 12,
					"maturation_period": "2days"
				},
				"resources": {
					"heap_size": 2000000000
				}
			},
			"search_settings": {
				"default_search_fields": [
					"title",
					"body"
				]
			},
			"retention": null
		},
		"checkpoint": {
			"_ingest-api-source": {},
			"_ingest-cli-source": {}
		},
		"create_timestamp": 1676998257,
		"sources": [
			{
				"version": "0.4",
				"source_id": "_ingest-cli-source",
				"max_num_pipelines_per_indexer": 1,
				"desired_num_pipelines": 1,
				"enabled": true,
				"source_type": "ingest-cli"
			},
			{
				"version": "0.4",
				"source_id": "_ingest-api-source",
				"max_num_pipelines_per_indexer": 1,
				"desired_num_pipelines": 1,
				"enabled": true,
				"source_type": "ingest-api"
			}
		]
	}'
```

Returns 200 OK when sending the body.

**Comment by fmassot** [comment] 2023-02-27 23:45
Interesting, I get a 301:

```bash
curl --request POST \
  --url http://127.0.0.1:7280/ \
  --header 'Content-Type: application/json' \
  --data '{}' --verbose
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:7280...
* Connected to 127.0.0.1 (127.0.0.1) port 7280 (#0)
> POST / HTTP/1.1
> Host: 127.0.0.1:7280
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 2
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< location: /ui/search
< content-length: 0
< date: Mon, 27 Feb 2023 23:44:59 GMT
<
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by ChillFish8** [comment] 2023-02-27 23:50
oh, that is indeed very interesting.

I get the 200 OK on both the latest docker image and the current main branch. :/

**Closed** 2023-02-28 11:48 UTC
Labels: bug
