### ISSUE TITLE
gRPC clients with connection problems will remain in the client pool

### ISSUE THREAD

**Issue by mosuka** [quickwit-oss/quickwit#148] opened 2021-06-23 01:15 UTC
Suppose the port for the GRPC is not open (due to a firewall, etc.).

The nodes in the cluster are using the SWIM protocol on different listen port to check each other's survival, so they appear to be alive to each other in the cluster.
In the client pool, this Lazy gRPC client remains even though the gRPC port is closed, so every time a search request comes in, some splits are assigned to that gRPC client, and then the search fails.

**Comment by fulmicoton** [comment] 2022-03-29 03:25
Duplicate of #1017

**Closed by fulmicoton** 2022-03-29 03:25 UTC
Labels: bug, good first issue
